"""Shared test isolation from local credentials and external services."""

from __future__ import annotations

import os


os.environ["QUAESTIO_DISABLE_DOTENV"] = "1"

_EXTERNAL_CONFIGURATION = {
    "QUAESTIO_LLM_BASE_URL",
    "QUAESTIO_LLM_API_KEY",
    "QUAESTIO_LLM_MODEL",
    "QUAESTIO_LLM_TIMEOUT_SECONDS",
    "QUAESTIO_SECONDARY_LLM_BASE_URL",
    "QUAESTIO_SECONDARY_LLM_API_KEY",
    "QUAESTIO_SECONDARY_LLM_MODEL",
    "QUAESTIO_TRANSLATION_MODE",
    "QUAESTIO_TRANSLATOR_BASE_URL",
    "QUAESTIO_TRANSLATOR_API_KEY",
    "QUAESTIO_TRANSLATOR_MODEL",
    "QUAESTIO_TRANSLATOR_TIMEOUT_SECONDS",
    "QUAESTIO_EMBEDDING_BASE_URL",
    "QUAESTIO_EMBEDDING_API_KEY",
    "QUAESTIO_EMBEDDING_MODEL",
    "QUAESTIO_EMBEDDING_TIMEOUT_SECONDS",
    "QUAESTIO_VERIFIER_LLM_BASE_URL",
    "QUAESTIO_VERIFIER_LLM_API_KEY",
    "QUAESTIO_VERIFIER_LLM_MODEL",
    "QUAESTIO_VERIFIER_LLM_TIMEOUT_SECONDS",
    "QUAESTIO_KNOWLEDGE_BASE_PATH",
}

for _name in _EXTERNAL_CONFIGURATION:
    os.environ.pop(_name, None)
